accounts/urls.py
from django.urls import path
from accounts.views import *


app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),

]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pid>', single_view, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', search_view, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

coinjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
import debug_toolbar

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),
    path('error', error_view, name='error'),
    path('password_reset', password_reset_view, name='password_reset'),
    path('password_reset/done', password_reset_done_view, name='password_reset_done'),
    path('password_reset_confirm/<str:username>/<str:uidb64>/<str:token>', password_reset_confirm_view, name='password_reset_confirm'),
    path('password_reset/complete', password_reset_complete_view, name='password_reset_complete'),
    path('maintenance/', maintenance, name='maintenance'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, forms
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/')

        form = forms.AuthenticationForm()
        context = {'form':form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/')

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'You have signed up successfully')
                return redirect('/')
            else:
                messages.add_message(request, messages.ERROR, "Try again")
        form = forms.UserCreationForm()
        context = {'form':form}
        return render(request, 'accounts/signup.html', context)

templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'stylesheet/bootstrap.min.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'stylesheet/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
      <img class="mb-4" src="{% static 'icon/favicon.png' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please Sign In</h1>
      <label for="inputEmail" class="sr-only">Username</label>
      <input type="text" name="username" class="form-control" placeholder="Username Or Email" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <p><li><a href="{% url 'website:password_reset' %}">Forgot Password?</a></li></p>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; Coinjet</p>
    </form>
  </body>
</html>

templates/accounts/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Signup</title>


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'stylesheet/bootstrap.min.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'stylesheet/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
      <img class="mb-4" src="{% static 'icon/favicon.png' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please Sign Up</h1>
      <label for="inputEmail" class="sr-only">Username</label>
      <input type="text" name="username" class="form-control" placeholder="Username" required autofocus><br>
      <label for="inputEmail" class="sr-only">Email</label>
      <input type="text" name="email" class="form-control" placeholder="Email" required><br>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" name="password1" class="form-control" placeholder="Password" required>
      <label for="inputPassword" class="sr-only">Confirm Password</label>
      <input type="password" name="password2" class="form-control" placeholder="Confirm Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
      <p class="mt-5 mb-3 text-muted">&copy; Coinjet</p>
    </form>
  </body>
</html>