blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pid>', single_view, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', search_view, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

coinjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
import debug_toolbar

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),
    path('error', error_view, name='error'),
    path('password_reset', password_reset_view, name='password_reset'),
    path('password_reset/done', password_reset_done_view, name='password_reset_done'),
    path('password_reset_confirm/<str:username>/<str:uidb64>/<str:token>', password_reset_confirm_view, name='password_reset_confirm'),
    path('password_reset/complete', password_reset_complete_view, name='password_reset_complete'),
    path('maintenance/', maintenance, name='maintenance'),
]

website/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

website/forms.py
from django import forms
from website.models import Contact, Newsletter
from captcha.fields import CaptchaField
from django.contrib.auth.models import User

class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = '__all__'

class NewsletterForm(forms.ModelForm):

    class Meta:
        model = Newsletter
        fields = '__all__'

class PasswordResetForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

website/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from website.forms import ContactForm, NewsletterForm, PasswordResetForm
from django.contrib import messages
from coinjet.settings import EMAIL_HOST_USER
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib.auth.forms import SetPasswordForm


def index_view(request):
    return render(request, 'website/index.html')

def about_view(request):
    return render(request, 'website/about.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your ticket submitted successfully')
        else:
            messages.add_message(request, messages.ERROR, "Your ticket didn't submitted")
    form = ContactForm()

    context = {'form':form}
    return render(request, 'website/contact.html', context)

def newsletter_view(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your email submitted successfully')
        else:
            messages.add_message(request, messages.ERROR, "Your email didn't submitted")
            
    form = NewsletterForm()

    return HttpResponseRedirect('/')

def error_view(request):
    return render(request, '404.html')

def password_reset_view(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            mail = form.cleaned_data.get('email')
            users = User.objects.filter(Q(email=mail))
            if users.exists():
                for user in users:
                    subject="reset password",
                    message="passwords/template_email.txt",
                    c = {
                    'username':user.username,
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
                    email = render_to_string(message, c)
                    try:				
                        send_mail(
                            subject,
                            email,
                            from_email=EMAIL_HOST_USER,
                            recipient_list=[mail],
                            fail_silently=False
                        )
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect('/password_reset/done')
            else:
                messages.add_message(request, messages.ERROR, "No such email in database.")

    form = PasswordResetForm()
    return render(request, 'passwords/password_reset.html', {'form':form})


def password_reset_done_view(request):
    return render(request, 'passwords/password_reset_done.html')

def password_reset_confirm_view(request, username, uidb64, token):
    user = User.objects.get(username=username)
    print (user)
    if request.method == 'POST':
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('/password_reset/complete')
        else:
            messages.add_message(request, messages.ERROR, "Your password is not as per password policy.")
    form = SetPasswordForm(user)
    context = {'form':form, 'username':username, 'uidb64':uidb64, 'token':token}
    return render(request, 'passwords/password_reset_confirm.html', context)

def password_reset_complete_view(request):
    return render(request, 'passwords/password_reset_complete.html')

def maintenance(request):
    return render(request, 'website/maintenance.html')

templates/website/contact.html
{% extends 'base.html' %}
{% block contact %}class="active"{% endblock contact %}
{% load static %}

{% block content %}
<div class="page-title">
    <div class="title-heading">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title-heading">
                        <h1 class="h1-title">CONTACT US</h1>
                    </div>
                    <ul class="breadcrumbs">
                        <li><a href="{% url 'website:index' %}" title="">Home</a></li>
                        <li class="dot">/</li>
                        <li>Contact us</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="flat-address-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="address-box center">
                    <div class="box-header">
                        <div class="icon">
                            <i class="fa fa-map-marker"></i>
                        </div>
                    </div>
                    <div class="box-content">
                        <h2>Address</h2>
                        <p>291 Proin Road, Lake Charles, Maine 11292</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="address-box center">
                    <div class="box-header">
                        <div class="icon">
                            <i class="fa fa-phone"></i>
                        </div>
                    </div>
                    <div class="box-content">
                        <h2>Phone number</h2>
                        <p>+1 234 800 8080</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="address-box center">
                    <div class="box-header">
                        <div class="icon">
                            <i class="fa fa-envelope-open"></i>
                        </div>
                    </div>
                    <div class="box-content">
                        <h2>Email</h2>
                        <p><a href="">example@gmail.com</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="flat-row flat-contact-form">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="top-title center">
                    <h2>CONTACT WITH US</h2>
                    <p>We'll help you resolve your issues quickly and easily.</p>
                </div>
                <div class="form-contact-form">
                    <form class="form-area contact-form text-right" action="{% url 'website:contact' %}" method="post">
                        <div class="row">
                            {% csrf_token %}
                            <div class="col-lg-6 form-group">
                                <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control"
                                    required="" type="text"><br>
    
                                <input name="email" placeholder="Enter email address"
                                    pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
                                    class="common-input mb-20 form-control" required="" type="email"><br>
    
                                <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control"
                                    type="text">
                            </div>
                            <div class="col-lg-6 form-group">
                                <textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'"
                                    required=""></textarea>
                            </div>
                            <div class="col-lg-12">
                                <div class="pb-3">
                                    {{form.captcha}}
                                </div>
                            <div class="alert-msg" style="text-align: left;"></div>
                            <button class="genric-btn primary" style="float: right;">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/website/cryptoinfo.html
<section class="flat-price-coin">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="top-title center">
                    <h2>CRYPTOCURRENCY PRICES</h2>
                    <p>The Bitcoin ecosystem at a glance. Any of our service with free test credits or actual
                        Bitcoins.</p>
                </div>
                <div class="table-price">
                    <table>
                        <thead>
                            <tr>
                                <th>Symbol</th>
                                <th>Name</th>
                                <th>USD</th>
                                <th>Change 24h</th>
                                <th>Change 7d</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>BTC</td>
                                <td>Bitcoin</td>
                                <td>{{b_price}}</td>
                                {% if b_day > 0 %}
                                    <td class="color-green">{{b_day}} %</td>
                                {% elif b_day < 0 %}
                                    <td class="color-red">{{b_day}} %</td>
                                {% else %}
                                    <td>{{b_day}} %</td>
                                {% endif %}
                                {% if b_week > 0 %}
                                    <td class="color-green">{{b_week}} %</td>
                                {% elif b_week < 0 %}
                                    <td class="color-red">{{b_week}} %</td>
                                {% else %}
                                    <td>{{b_week}} %</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>ETH</td>
                                <td>Ethereum</td>
                                <td>{{e_price}}</td>
                                {% if e_day > 0 %}
                                    <td class="color-green">{{e_day}} %</td>
                                {% elif e_day < 0 %}
                                    <td class="color-red">{{e_day}} %</td>
                                {% else %}
                                    <td>{{e_day}} %</td>
                                {% endif %}
                                {% if e_week > 0 %}
                                    <td class="color-green">{{e_week}} %</td>
                                {% elif e_week < 0 %}
                                    <td class="color-red">{{e_week}} %</td>
                                {% else %}
                                    <td>{{e_week}} %</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>XRP</td>
                                <td>Ripple</td>
                                <td>{{r_price}}</td>
                                {% if r_day > 0 %}
                                    <td class="color-green">{{r_day}} %</td>
                                {% elif r_day < 0 %}
                                    <td class="color-red">{{r_day}} %</td>
                                {% else %}
                                    <td>{{r_day}} %</td>
                                {% endif %}
                                {% if r_week > 0 %}
                                    <td class="color-green">{{r_week}} %</td>
                                {% elif r_week < 0 %}
                                    <td class="color-red">{{r_week}} %</td>
                                {% else %}
                                    <td>{{r_week}} %</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>LTC</td>
                                <td>Litecoin</td>
                                <td>{{l_price}}</td>
                                {% if l_day > 0 %}
                                    <td class="color-green">{{l_day}} %</td>
                                {% elif l_day < 0 %}
                                    <td class="color-red">{{l_day}} %</td>
                                {% else %}
                                    <td>{{l_day}} %</td>
                                {% endif %}
                                {% if l_week > 0 %}
                                    <td class="color-green">{{l_week}} %</td>
                                {% elif l_week < 0 %}
                                    <td class="color-red">{{l_week}} %</td>
                                {% else %}
                                    <td>{{l_week}} %</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td>XMR</td>
                                <td>Monero</td>
                                <td>{{m_price}}</td>
                                {% if m_day > 0 %}
                                    <td class="color-green">{{m_day}} %</td>
                                {% elif m_day < 0 %}
                                    <td class="color-red">{{m_day}} %</td>
                                {% else %}
                                    <td>{{m_day}} %</td>
                                {% endif %}
                                {% if m_week > 0 %}
                                    <td class="color-green">{{m_week}} %</td>
                                {% elif m_week < 0 %}
                                    <td class="color-red">{{m_week}} %</td>
                                {% else %}
                                    <td>{{m_week}} %</td>
                                {% endif %}
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

templates/website/latestposts.html
{% load static %}
{% load humanize %}

<section class="flat-news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="top-title center">
                    <h2>Recent Posts</h2>
                    <p>We are the world's premier 24/7 news feed covering everything bitcoin-related.</p>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4">
                <article class="main-post news three-column">
                    <div class="featured-post">
                        <a href="{% url 'blog:single' pid=post.id %}" title="">
                            <img src="{{post.image.url}}" alt="" />
                        </a>
                    </div>
                    <div class="entry-content">
                        <h2>
                            <a href="{% url 'blog:single' pid=post.id %}" title="">{{post.title}}</a>
                        </h2>
                        <ul class="meta-left">
                            <li class="post-author">
                                <i class="fa fa-user"></i> {{post.author}}
                            </li>
                            <li class="post-date">
                                <i class="fa fa-calendar"></i> {{post.published_date|naturalday}}
                            </li>
                            <li class="post-view">
                                <i class="fa fa-eye"></i> {{post.counted_views}}
                            </li>
                        </ul>
                        <p>
                            {{post.content|truncatewords:10}}
                        </p>
                    </div>
                </article>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/website/maintenance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Site Maintenance</title>

    <style>
      body { text-align: center; padding: 150px; }
      h1 { font-size: 50px; }
      body { font: 20px Helvetica, sans-serif; color: #333; }
      article { display: block; text-align: left; width: 650px; margin: 0 auto; }
      a { color: #dc8100; text-decoration: none; }
      a:hover { color: #333; text-decoration: none; }
    </style>
</head>
<body>
<article>
        <h1>We&rsquo;ll be back soon!</h1>
        <div>
            <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need to you can always <a href="mailto:a.rafiei1375@gmail.com">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
            <p>&mdash; Coinjet Team</p>
        </div>
    </article>

</body>
</html>