blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pid>', single_view, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', search_view, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

coinjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
import debug_toolbar

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),
    path('error', error_view, name='error'),
    path('password_reset', password_reset_view, name='password_reset'),
    path('password_reset/done', password_reset_done_view, name='password_reset_done'),
    path('password_reset_confirm/<str:username>/<str:uidb64>/<str:token>', password_reset_confirm_view, name='password_reset_confirm'),
    path('password_reset/complete', password_reset_complete_view, name='password_reset_complete'),
    path('maintenance/', maintenance, name='maintenance'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg') 
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(null=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

    

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'message']

blog/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import CommentForm
from django.contrib import messages

def blog_view(request, **kwargs):
    # determining which post to show based on publish date
    now = timezone.now()
    posts = Post.objects.filter(published_date__lte=now)
    # setting status for published posts
    for post in posts:
        post.status = True
        post.save()
    # category division
    if kwargs.get('cat_name') !=None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    # tag division
    if kwargs.get('tag_name') !=None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    # author division
    if kwargs.get('author_username') !=None:
        posts = posts.filter(author__username=kwargs['author_username'])

    #paginating
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    context = {'posts':posts}
    return render(request, 'blog/blog.html', context)

def single_view(request, pid):
    try:
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Your comment submitted successfully')
            else:
                messages.add_message(request, messages.ERROR, "Your comment didn't submitted")

        post = Post.objects.get(id=pid, status=True)
        # counted view adding method
        post.counted_views += 1
        post.save()
        
        #comments
        comments = Comment.objects.filter(post=post.id, approved=True)

        form = CommentForm()
        context = {'post':post, 'comments':comments, 'form':form}
        return render(request, 'blog/blog-single.html', context)    
    except:
        return redirect('/error')

def search_view(request):
    posts = Post.objects.filter(status=True)
    if request.method == 'GET':
        posts = posts.filter(content__contains=request.GET.get('s'))

    context = {'posts':posts}
    return render(request, 'blog/blog.html', context)

templates/blog/blog-single.html
{% extends 'base.html' %}
{% block blog %}class="active"{% endblock blog %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="page-title">
    <div class="title-heading">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title-heading">
                        <h1 class="h1-title">{{post.title}}</h1>
                    </div>
                    <ul class="breadcrumbs">
                        <li><a href="{% url 'blog:blog' %}" title="">Blog</a></li>
                        <li class="dot">/</li>
                        <li>{{post.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <article class="main-post main-single">
                    <div class="featured-post">
                        <a href="#" title="">
                            <img src="{{post.image.url}}" alt="" />
                        </a>
                    </div>
                    <div class="entry-title">
                        <h2>
                            {{post.title}}
                        </h2>
                        <ul class="meta-left">
                            <li class="post-tags">
                                <i class="fa fa-star"></i>
                                {% for cat in post.category.all %}
                                    <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </li>
                            <li class="post-author">
                                <i class="fa fa-user"></i>
                                <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author}}</a>
                            </li>
                            <li class="post-date">
                                <i class="fa fa-calendar"></i> {{post.published_date|date:"d M Y"}}
                            </li>
                            <li class="post-view">
                                <i class="fa fa-eye"></i> {{post.counted_views}}
                            </li>
                            <li class="post-comment">
                                <i class="fa fa-comment"></i> {{comments|length}}
                            </li>
                        </ul>
                    </div>
                    <div class="entry-content">
                        <p>
                            {{post.content}}
                        </p>
                    </div>
                    <div class="direction">
                        <ul class="social">
                            <li>
                                <a href="#" title="">
                                    <i class="fa fa-facebook-f"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="">
                                    <i class="fa fa-pinterest" aria-hidden="true"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" title="">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                        </ul>
                        <div class="widget_tag_cloud">
                            <div class="tag-cloud">
                                {% for tag in post.tags.all %}
                                <a href="{% url 'blog:tag' tag_name=tag.name %}" title="" class="tag-link">{{tag.name}}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    
                </article>
                <div class="comment-single">
                    <div class="comment-area">
                        <h3>{{comments|length}} Comments</h3>
                        <ol class="comment-list">
                            {% for comment in comments %}
                            <li class="comment">
                                <article class="comment-body">
                                    <div class="comment-image">
                                        <img src="{% static 'images/blog/comment-01.jpg' %}" alt="">
                                    </div>
                                    <div class="comment-text">
                                        <div class="comment-metadata">
                                            <div class="name">
                                                {{comment.name}} <span class="date"><i class="fa fa-clock-o"
                                                        aria-hidden="true"></i> {{comment.created_date|naturalday}}</span>
                                            </div>
                                        </div>
                                        <div class="comment-content">
                                            <p>{{comment.message}}</p>
                                        </div>
                                        <div class="reply"><a href="#" title="">Reply</a></div>
                                    </div>    
                                </article>
                                <!--
                                <ol class="children">
                                    <li class="comment">
                                        <article class="comment-body">
                                            <div class="comment-image">
                                                <img src="{% static 'images/blog/comment-02.jpg' %}" alt="">
                                            </div>
                                            <div class="comment-text">
                                                <div class="comment-metadata">
                                                    <div class="name">
                                                        Linda Thompson <span class="date"><i class="fa fa-clock-o"
                                                                aria-hidden="true"></i> 12
                                                            Feb 2018</span>
                                                    </div>
                                                </div>
                                                <div class="comment-content">
                                                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr,
                                                        sed diam nonumy eirmod tempor invidunt ut labore et
                                                        dolore magna aliquyam erat, sed diam voluptua. At vero
                                                        eos et.</p>
                                                </div>
                                                <div class="reply"><a href="#" title="">Reply</a></div>
                                            </div>
                                        </article>
                                    </li>
                                </ol>
                                -->
                            </li>
                            {% empty %}
                            <p> No comments here yet. Be the first one to tell your thoughts. </p>
                            {% endfor %}
                        </ol>
                    </div>
                    <div class="comment-respond">
                        <h2>Leave your comment</h2>
                        <form action="{% url 'blog:single' pid=post.id %}" method="post" accept-charset="utf-8">
                            {% csrf_token %}
                            <input type="hidden" name="post" value="{{post.id}}">
                            {% if request.user.is_authenticated %}
                            <input type="hidden" name="name" value="{{request.user.username}}">
                            <input type="hidden" name="email" value="{{request.user.email}}">
                            {% else %}
                            <div class="comment-form-name">
                                <input type="text" name="name" placeholder="Your Name">
                            </div>
                            <div class="comment-form-email">
                                <input type="text" name="email" placeholder="Your Email">
                            </div>
                            {% endif %}
                            <div class="comment-form-comment">
                                <textarea name="message" placeholder="Your Message"></textarea>
                            </div>
                            <div class="comment-form-submit">
                                <button type="submit">SEND COMMENT</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}
{% block blog %}class="active"{% endblock blog %}
{% load static %}
{% load blog_tags %}

{% block content %}
<div class="page-title">
    <div class="title-heading">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title-heading">
                        <h1 class="h1-title">BLOG</h1>
                    </div>
                    <ul class="breadcrumbs">
                        <li><a href="{% url 'website:index' %}" title="">Home</a></li>
                        <li class="dot">/</li>
                        <li>Blog</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-4">
                <div class="sidebar">
                    <aside class="widget widget_search">
                        <h2 class=widget-title>Search Here</h2>
                        <form action="{% url 'blog:search' %}" method="get" accept-charset="utf-8">
                            <div class="input-search">
                                <input type="text" name="s" />
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </aside>

                    {% popularposts %}

                    {% posttags %}
                 
                    {% postcategories %}

                </div>
            </div>
            <div class="col-lg-9 col-md-8">
                <div class="post-wrap">
                    {% for post in posts %}
                    <article class="main-post">
                        <div class="featured-post">
                            <a href="{% url 'blog:single' pid=post.id %}" title="">
                                <img src="{{post.image.url}}" alt="" />
                            </a>
                        </div>
                        <div class="entry-content">
                            <h2>
                                <a href="{% url 'blog:single' pid=post.id %}" title="">{{post.title}}</a>
                            </h2>
                            <p>
                                {{post.content|truncatewords:15}}
                            </p>
                            <br>
                            <p align="right">
                                <a href="{% url 'blog:single' pid=post.id %}" class="read-more" title="">READ MORE</a>
                            </p>
                        </div>
                        <ul class="meta-left">
                            <li class="post-tags">
                                <i class="fa fa-star"></i>
                                {% for cat in post.category.all %}
                                    <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </li>
                            <li class="post-author">
                                <i class="fa fa-user"></i>
                                <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author}}</a>
                            </li>
                            <li class="post-date">
                                <i class="fa fa-calendar"></i> {{post.published_date|date:"d M Y"}}
                            </li>
                            <li class="post-view">
                                <i class="fa fa-eye"></i> {{post.counted_views}}
                            </li>
                            <li class="post-comment">
                                <i class="fa fa-comment"></i> {% comments_count post.id %}
                            </li>
                        </ul>
                    </article>
                    {% endfor %}
                    <div class="blog-pagination left">
                        <ul class="flat-pagination">
                            {% if posts.has_previous %}
                            <li><a href="?page={{posts.previous_page_number}}" title=""><i class="fa fa-angle-left" aria-hidden="true"></i></a>
                            {% endif %}
                            {% for i in posts.paginator.page_range %}
                                {% if posts.number == i %}
                                    <li><a href="?page={{i}}" title="" class="active">{{i}}</a></li>
                                {% else %}
                                    <li><a href="?page={{i}}" title="">{{i}}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if posts.has_next %}
                            <li><a href="?page={{posts.next_page_number}}" title=""><i class="fa fa-angle-right" aria-hidden="true"></i></a>
                            {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/blog/popularposts.html
{% load static %}
{% load humanize %}

<aside class="widget widget-recent-news">
    <h2 class=widget-title>Popular posts</h2>
    <ul class="recent-news">
        {% for post in posts %}
        <li>
            <div class="post-image" style="max-width:130px;">
                <a href="{% url 'blog:single' pid=post.id %}" title=""><img src="{{post.image.url}}"
                        alt=""></a>
            </div>
            <div class="post-content">
                <h5>
                    <a href="{% url 'blog:single' pid=post.id %}" title="">{{post.title}}</a>
                </h5>
                <ul class="meta-left">
                    <li class="post-author">
                        <i class="fa fa-user"></i> {{post.author}}
                    </li>
                    <li class="post-view">
                        <i class="fa fa-eye"></i> {{post.counted_views}}
                    </li>
                    <li class="post-date">
                        <i class="fa fa-calendar"></i> {{post.published_date|naturalday}}
                    </li>
                </ul>
            </div>
        </li>
        {% endfor %}
    </ul>
</aside>

templates/blog/postcategories.html
<aside class="widget widget_categories">
    <h2 class=widget-title>Categories</h2>
    <ul>
        {% for name,count in categories.items %}
        <li class="cat-item">
            <a href="{% url 'blog:category' cat_name=name %}" title="">
                <p style="text-align:left;">
                    {{name}}
                    <span style="float:right;">
                        {{count}}
                    </span>
                </p>
            </a>
        </li>
        {% endfor %}
    </ul>
</aside>

templates/blog/posttags.html
<aside class="widget widget_tag_cloud">
    <h2 class="widget-title">Tags</h2>
    <div class="tag-cloud">
        {% for tag in tags %}
            <a href="{% url 'blog:tag' tag_name=tag %}" title="" class="tag-link">{{tag}}</a>
        {% endfor %}
    </div>
</aside>