accounts/urls.py
from django.urls import path
from accounts.views import *


app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),

]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog'),
    path('<int:pid>', single_view, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', search_view, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
]

coinjet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap
import debug_toolbar

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter', newsletter_view, name='newsletter'),
    path('error', error_view, name='error'),
    path('password_reset', password_reset_view, name='password_reset'),
    path('password_reset/done', password_reset_done_view, name='password_reset_done'),
    path('password_reset_confirm/<str:username>/<str:uidb64>/<str:token>', password_reset_confirm_view, name='password_reset_confirm'),
    path('password_reset/complete', password_reset_complete_view, name='password_reset_complete'),
    path('maintenance/', maintenance, name='maintenance'),
]

templates/base.html
{% load static %}
{% load compress %}
{% include 'message.html' %}
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<!--<![endif]-->

<head>

    <meta charset="UTF-8">
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
    <title>Coinjet</title>
    <meta name="author" content="themsflat.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/layers.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'revolution/css/settings.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet/fancybox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet/colors/color1.css' %}" id="colors">
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheet/responsive.css' %}">
    {% endcompress %}
    <link href="{% static 'icon/apple-touch-icon-48-precomposed.png' %}" rel="apple-touch-icon-precomposed">
    <link href="{% static 'icon/apple-touch-icon-32-precomposed.png' %}" rel="apple-touch-icon-precomposed">
    <link href="{% static 'icon/favicon.png' %}" rel="shortcut icon">
</head>

<body>
    <div class="boxed">

        <div id="loading-overlay">
            <div class="loader"></div>
        </div>
        <div class="themesflat-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="box-account">
                            {% if request.user.is_authenticated %}
                            <li class="login">
                                <a href="#" title="">Logged in as {{request.user.username}}</a>
                            </li>
                            <li class="sign-in">
                                <a href="{% url 'accounts:logout' %}" title="">Logout</a>
                            </li>
                            {% else %}
                            <li class="login">
                                <a href="{% url 'accounts:login' %}" title="">Login</a>
                            </li>
                            <li class="sign-in">
                                <a href="{% url 'accounts:signup' %}" title="">Signup</a>
                            </li>
                            {% endif %}
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <header id="header" class="header bg-color">
            <div class="container">
                <div class="row">
                    <div class="header-wrap">
                        <div id="logo" class="logo">
                            <a href="{% url 'website:index' %}" title="">
                                <img src="{% static 'images/logo.png' %}" alt="logo Finance Business" />
                            </a>
                        </div>
                     
                        <div class="nav-wrap">
                            <div class="btn-menu">
                                <span></span>
                            </div>
                            <nav id="mainnav" class="mainnav">
                                <ul class="menu">
                                    <li {% block home %}{% endblock home %}>
                                        <a href="{% url 'website:index' %}" title="">HOME</a>
                                    </li>
                                    <li {% block about %}{% endblock about %}>
                                        <a href="{% url 'website:about' %}" title="">ABOUT</a>
                                    </li>
                                    <li {% block blog %}{% endblock blog %}>
                                        <a href="{% url 'blog:blog' %}" title="">BLOG</a>
                                    </li>
                                    <li {% block contact %}{% endblock contact %}>
                                        <a href="{% url 'website:contact' %}" title="">CONTACT</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% block content %}

        {% endblock %}

        <footer id="footer_background">
            <div class="footer">
                <div class="container">
                    <div class="row">
                        <div class="footer-widgets">
                            <div class="col-md-4">
                                <div class="widget widget-about">
                                    <div class="widget-text">
                                        <div id="logo-ft">
                                            <a href="#" title="">
                                                <img src="{% static 'images/logo-ft.png' %}" alt="">
                                            </a>
                                        </div>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a rhoncus risus
                                            atione Pellentesque sodales risus aut
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="widget widget-newletter">
                                    <h3 class="widget-title">NEWSLETTER</h3>
                                    <form action="{% url 'website:newsletter' %}" method="post" accept-charset="utf-8">
                                        {% csrf_token %}
                                        <div id="subscribe-content">
                                            <div class="input-email">
                                                <input type="email" name="email" id="subscribe-email"
                                                    placeholder="Email address">
                                            </div>
                                            <button type="submit" id="subscribe-button" class="button-subscribe"><i
                                                    class="fa fa-paper-plane" aria-hidden="true"></i></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="widget widget_contact">
                                    <h3 class="widget-title">CONTACT</h3>
                                    <ul class="contact-list">
                                        <li>
                                            Address: <span>9291 Proin Road, Lake Charles Maine 11292</span>
                                        </li>
                                        <li>
                                            Phone: <span>+1 234 800 8080</span>
                                        </li>
                                        <li>
                                            Email: <span>example@gmail.com</span>
                                        </li>
                                    </ul>
                                    <div class="widget widget_themesflat_socials">
                                        <ul class="themesflat-shortcode-socials">
                                            <li class="facebook">
                                                <a href="#" target="_blank" rel="alternate" title="">
                                                    <i class="fa fa-facebook"></i>
                                                </a>
                                            </li>
                                            <li class="twitter">
                                                <a href="#" target="_blank" rel="alternate" title="">
                                                    <i class="fa fa-twitter"></i>
                                                </a>
                                            </li>
                                            <li class="google-plus">
                                                <a href="#" target="_blank" rel="alternate" title="t;">
                                                    <i class="fa fa-google-plus"></i>
                                                </a>
                                            </li>
                                            <li class="instagram">
                                                <a href="#" target="_blank" rel="alternate" title="">
                                                    <i class="fa fa-instagram"></i>
                                                </a>
                                            </li>
                                            <li class="linkedin">
                                                <a href="#" target="_blank" rel="alternate" title="">
                                                    <i class="fa fa-linkedin"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="copyright">
                                <p>© Copyright <a href="#" title="">Coinjet</a> Cryptocurrency Theme by <a
                                        href="https://themeforest.net/user/themesflat/portfolio" title="">Themesflat</a>
                                    2018</p>
                                <p>© Powered by <a href="https://coinlib.io/apidocs" title="">Coinlip API</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <div class="button-go-top">
            <a href="#" title="" class="go-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>
    </div>
    {% compress js %}
    <script type="text/javascript" src="{% static 'javascript/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/tether.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/jquery.flexslider-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/owl.carousel.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/jquery.easing.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/jquery-countTo.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/waypoints.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/jquery.fancybox.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/kinetic.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/images-loaded.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/equalize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'javascript/main.js' %}"></script>

    <script type="text/javascript" src="{% static 'revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'revolution/js/slider_v1.js' %}"></script>

    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.carousel.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.kenburn.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.migration.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.parallax.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script type="text/javascript"
        src="{% static 'revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    {% endcompress %}
</body>

</html>

templates/message.html
{% for message in messages %}
  <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-header">
      <strong class="mr-auto">
        {% if message.tags == 'error' %}
          <i class="fa fa-times mr-2"></i>
        {% elif message.tags == 'warning' %}
          <i class="fa fa-exclamation mr-2"></i>
        {% elif message.tags == 'info' %}
          <i class="fa fa-info mr-2"></i>
        {% elif message.tags == 'success' %}
          <i class="fa fa-flag mr-2"></i>
        {% endif %}
        {{message.tags|capfirst}}
      </strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      {{message|safe}}
    </div>
  </div>
{% endfor %}

templates/simple_message.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
    {% endfor %}
    </ul>
{% endif %}